spring:

  datasource:

    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/course

    username: postgres

    password: admin


flyway:

  url: jdbc:postgresql://localhost:5432/course

  user: postgres

  password: admin

  enabled: true

  locations:

    - 'classpath:db/migration'